""" example for extracting single reaction rates from experimental results 
for use in spectra-uf
"""
from nfoils.activity import ReactionRateRetrieval

# folder to look into
exp_folder = 'proton_march24'

# name of the results file generated by calculate_exp_activities
results_file_name = 'e_results.json'

# initialise and run
retriever = ReactionRateRetrieval()
retriever.run(exp_folder,results_file_name)

