""" do a calculated/experimental analysis for activation foil results. 
the experimental results file should have one dataset from one experiment.
the calculated results file can have up to three datasets from 
different nuclear data library simulations with FISPACT 

Use after get_activites.py, which generates the 'e_results' file.
The FISPACT simulation results should be contained in 'data/c_results'
"""
from nfoils.ce import CEPlotter

# path to the calculated and experimental results files to analyse
# the final C/E plot will also be saved here
folder = '.'

# name to save the C/E plot under as a PNG
plotname = 'test'

# initialise object
ce_plotter = CEPlotter(folder,plotname)

# name of experimental json results file, generated by get_activities.py
exp_results = 'e_results'

# name of the calculated json results file
# see the file for the specific format
# must list same isotopes in the same order as the experimental results file
# for each isotope, includes:
#  foil_weight in grams
#  mathmode name for the isotope i.e. "$^{56}Mn$"
#  list of activities in Bq/g for the libraries used in fispact sims
#  list of fractional uncertainties for the above fispact activities
#  isotopic fractional uncertainty for the spectrum used
#  self shielding factor, taken from the fispact calculation
calc_results = 'data/c_results'

# input the plot labels for the libraries you used in fispact sims
# (up to three permitted)
# put these in the same order as the results in the c_results file
libraries = ['TENDL-2021','IRDFF-II','ENDF/B-VIII']

# Normalisation to rescale calculated results by, if needed
flux_norm_mean = 1

# Fractional uncertainty on the flux estimation
flux_frac_error = 0.05

# reorder the isotopes in your results files e.g. into capture-to-threshold
# 0 will be the first isotope listed in c_results and e_results
# [2,1,0] would reverse the order of a three-isotope list in the final plot
order = [2,1,0] 

# out of the new list, which isotopes do you want a C/E weighted average for?
# e.g. [5,20] will calculate a weighted average for isotopes 5-->20 
# in the new list
we_isotopes = [0,3]

# which library dataset to use for the weighted average analysis?
we_library = 'IRDFF-II'

# would you like to add black vertical lines to split the plot up? 
# i.e. [4.5,13.5] puts lines between isotopes 4 and 5, and isotopes 13 and 14
# in the new list
plot_split_list = [4.5,13.5]

# set y axis size for C/E plot e.g. [0,2] for 0-->2
y_axis = [0.1,2.3]

# set how far along the x axis to place the legend
legend_x_coord = 0.05

# get c/e plot with red uncertainty band representing combined 
# uncertainty from isotopic neutron spectrum and flux estimation. 
# C/E error bar uncertainties values are from C and E uncertainties:
# C value errors include (a) FISPACT uncertainties 
# (b) isotopic neutron spectrum uncertainty, (c) flux estimation uncertainty
# E value errors include (a) peak fitting (b) efficiency calibration
# also do weighted ave analysis for specified isotopes
ce_plotter.run(calc_results,exp_results,flux_norm_mean,
               flux_frac_error,we_isotopes,libraries,
               order,plot_split_list,y_axis,we_library,
               legend_x_coord)
