""" do a calculated/experimental analysis for activation foil results. 
the experimental results file should have one dataset from one experiment.
the calculated results file can have up to three datasets from 
different nuclear data library simulations with FISPACT 

Use after get_activites.py, which generates the 'e_results' file.
The FISPACT simulation results should be contained in 'data/c_results'
"""
from nfoils.ce import CEPlotter

# path to the calculated and experimental results files to analyse
# the final C/E plot will also be saved here
folder = '.'

# name of experimental json results file, generated by get_activities.py
exp_results = 'results/e_results'

# name of the calculated json results file
# see the file for the specific format
# must list same isotopes in the same order as the experimental results file
# for each isotope, includes:
#  foil_weight in grams
#  mathmode name for the isotope i.e. "$^{56}Mn$"
#  list of activities in Bq/g for the libraries used in fispact sims
#  list of fractional uncertainties for the above fispact activities
#  isotopic fractional uncertainty for the spectrum used
#  self shielding factor, taken from the fispact calculation
calc_results = 'data/c_results'

# input the plot labels for the libraries you used in fispact sims
# (up to three permitted)
# put these in the same order as the results in the c_results file
libraries = ['TENDL-2021','IRDFF-II','ENDF/B-VIII']

# Fractional uncertainty on the flux estimation
flux_frac_error = 0.05

# out of the new list, which isotopes do you want a C/E weighted average for?
# e.g. [5,20] will calculate a weighted average for isotopes 5-->20 
# in the new list
we_isotopes = [0,3]

# which library dataset to use for the weighted average analysis?
we_library = 'IRDFF-II'

# get c/e plot with red uncertainty band representing combined 
# uncertainty from isotopic neutron spectrum and flux estimation. 
# C/E error bar uncertainties values are from C and E uncertainties:
# C value errors include (a) FISPACT uncertainties 
# (b) isotopic neutron spectrum uncertainty, (c) flux estimation uncertainty
# E value errors include (a) peak fitting (b) efficiency calibration
# also do weighted ave analysis for specified isotopes
ce_plotter = CEPlotter(folder)
ce_plotter.run(calc_results,exp_results,libraries,flux_frac_error,
               we_isotopes,we_library)
