""" example for extracting single reaction rate data for unfolding an 
incident particle energy spectrum
"""
from bfoils.activity import ReactionRateRetrieval

# folder to look into and print results
exp_folder = '.'

# name of the results file generated by calculate_e_results.py
results_file_name = 'e_results.json'

# get new folder containing reaction rates, uncertainties and isotopes
# in txt format for reading by unfolding module
retriever = ReactionRateRetrieval()
retriever.run(exp_folder,results_file_name)

