""" do calculated/experimental analysis for activation
foil results. The necessary 'e_results' file should be generated by 
calculate_e_results.py beforehand
"""

from nfoils.ce import CEPlotter

# path to the calculated and experimental results files to analyse
# the final C/E plot will also be saved here
folder = 'example'

# name to save the C/E plot under as a PNG
plotname = 'test'

# initialise object
ce_plotter = CEPlotter(folder,plotname)

# names of calculated and experimental json results files
# see the files themselves for the formats required
calc_results = 'c_results'
exp_results = 'e_results'

# input the plot labels for the three libraries you are analysing
# put these in the same oder as they are in the c_results file
libraries = ['TENDL-2021','IRDFF-II','ENDF/B-VIII']

# Flux normalisation to scale C results by, if needed
flux_norm_mean = 1.1

# Fractional uncertainty on the flux estimation, to incorporate into the 
# C/E uncertainty analysis
flux_frac_error = 0.05

# reorder the isotopes in your results files 
# e.g. reoder them into capture-to-threshold. 0 will be the first isotope in 
# c_results and e_results
order = [10,2,15,16, 6,19,7,9,12,13,4,5,0,3,1,14,11] 

# out of the new list, which isotopes do you want a C/E weighted average for?
# e.g. [5,20] will calculate a weighted average for isotopes 5-->20 
# in the new list
we_isotopes = [5,20]

# which library dataset would you like to use for the weighted average calcs?
we_library = 'ENDF/B-VIII'

# would you like to add black vertical lines to split the plot up? 
# i.e. [4.5,13.5] puts lines between isotopes 4 and 5, and isotopes 13 and 14
# in the new list
plot_split_list = [4.5,13.5]

# set y axis size for C/E plot e.g. [0,2] for 0-->2
y_axis = [0.01,2.3]

# set how far along the x axis to place the legend
legend_x_coord = 0.8

#do c/e plot and weighted ave analysis
ce_plotter.run(calc_results,exp_results,flux_norm_mean,
               flux_frac_error,we_isotopes,libraries,
               order,plot_split_list,y_axis,we_library,
               legend_x_coord)
