""" example for extracting single reaction rates to csv lists for unfolding 
with spectra-uf. Use after calculate_e_results.py, which generates e_results
"""
from nfoils.activity import ReactionRateRetrieval

# folder to look into and print results
exp_folder = '.'

# name of the results file generated by calculate_e_results.py
results_file_name = 'e_results'

# get new folder containing reaction rates, uncertainties and isotopes
# in csv format for reading by spectra-uf
retriever = ReactionRateRetrieval()
retriever.run(exp_folder,results_file_name)

