""" example for extracting single reaction rates from experimental results 
for unfolding. Use after calculate_e_results.py, which calculates RRs
"""
from nfoils.activity import ReactionRateRetrieval

# folder to look into
exp_folder = 'example'

# name of the results file generated by calculate_exp_activities
results_file_name = 'e_results'

# initialise and run
retriever = ReactionRateRetrieval()
retriever.run(exp_folder,results_file_name)

