""" sum job-generated ascii files together 
and plot the resulting summed spectrum
"""
from nfoils.ascii import AsciiSummer

# path to dir with multiple ascii spectra generated by a job file inside
# should be in normal ascii format
folder_path = 'example_asciis'

# name of job-generated ascii files without the 'xxx' numbers at the end 
# e.g. if the files are spectrum_000,spectrum_001... then input 'spectrum'
ascii_filetag = 'uBB_20s_x60_20mins'

# list of file numbers to sum together i.e. [0,3] = '000' to '003'
file_numbers = [0,3]

# sum the asciis together in one new file and plot the resulting spectrum
ascii_summer = AsciiSummer(folder_path,ascii_filetag,file_numbers)
ascii_summer.run()